### ISSUE TITLE
3.0.18 - Not possible to specify platform version

### ISSUE THREAD

**Issue by joaocsilva** [ec-europa/toolkit#133]
I was testing the release 3.0.18 and is not possible anymore to set a custom platform version.
```
...
- Installing ec-europa/toolkit (3.0.18): Downloading (100%)
...
> project-platform-set-version:
[echo] The platform package version is set to 2.5.112.
[echo] The build will be performed with version 2.5.135.3.
```

There's a PR https://github.com/ec-europa/digital-transformation-dev/pull/2970
There's a Drone build https://drone.fpfis.eu/ec-europa/digital-transformation-dev/715/18

At the drone you can look at the **setup** and then to the **build**.

**Comment by jonhy81** [comment]
Hi @joaocsilva , it was fixed in 3.0.19 closing.
