### ISSUE TITLE
[project-database-file] use variable which is not defined and not used

### ISSUE THREAD

**Issue by LOBsTerr** [ec-europa/toolkit#62]
### issue
I tried to debug production db import and found that in project-database-file there is a variable **project.db.file** which is not defined anywhere and not used anywhere else.

### Solution
Replace it with a proper variable

**Comment by jonhy81** [comment]
Hi @LOBsTerr, the target is designed to discover the filename by itseld, that is why is empty by default. We kept the variable to some edge case when you want specify it for some specific dump.
