### ISSUE TITLE
 [warning] Use of undefined constant DRUPAL_ROOT

### ISSUE THREAD

**Issue by LOBsTerr** [ec-europa/toolkit#80]
I am currently trying to run "install-clone".
I see this warning 
```
[warning] Use of undefined constant DRUPAL_ROOT - assumed 'DRUPAL_ROOT' (this will throw an Error in a future version of PHP) sites.php:9
```

Version: ec-europa/toolkit 3.0.4 NextEuropa Toolkit packaged for composer

**Comment by verbruggenalex** [comment]
Fixed with newest fpfis deploy package.
